### ISSUE TITLE
(4) Evaluate models

### ISSUE THREAD

**Issue by redouane-dziri** [redouane-dziri/deep-music-classification#11]
On test set:

- [x] Accuracy (piece level)
- [x] Implement majority voting of the short-term pieces for each track - how to break ties? randomly ?
- [x] Accuracy (track level)
- [x] Accuracy per genre (piece level)

- Not MSE

**Comment by redouane-dziri** [comment]
A notebook that loads a model and evaluates it on the test set

**Comment by arnaudstiegler** [comment]
All done with an evaluation folder that contains two notebooks that:
- generate the predictions on the test set for each model
- compute the metrics for piece-level and track-level (with majority voting)

Note that the "Class accuracy" is going to be the precision per genre
