### ISSUE TITLE
Incorrect dump for MFCC

### ISSUE THREAD

**Issue by arnaudstiegler** [redouane-dziri/deep-music-classification#12]
The dump for the MFCC is incorrect, I think the function that generates it is correct, but not the one generating the dict... So there is an issue somewhere in there. I'll fix that soon

**Comment by arnaudstiegler** [comment]
@redouane-dziri,
Quick question about the MFCCs. The 30 submaps mentioned in the paper are supposed to be stacked together, or are they supposed to be standalone items? (Are we training the model on the stack or on each single submap?)

**Comment by redouane-dziri** [comment]
don't remember, look at paper
