### ISSUE TITLE
Saving model to .h5 with custom layer

### ISSUE THREAD

**Issue by arnaudstiegler** [redouane-dziri/deep-music-classification#14]
When running a simple `model.save("my_model.h5")`, we got the following error:
`RuntimeError: Unable to create link (name already exists)`

Likely due to the fact that the model has a custom layer

**Comment by arnaudstiegler** [comment]
So, two small changes to make it work:

- model.save(): it was raising an error because of the fact that the custom layer variables had no name, and therefore could not be fetched from the config of the layer. To solve that, I just added a `name=...` in the `add_weight()` for both b and w
- model.load(): since we have a custom layer, we need to pass the custom layer object to the function so that it can create the model. So you have to add to the function the following argument: `custom_objects={'AffineScalar':AffineScalar()}`

Reproducible code at `playground/keras_custom_model_save.ipynb`

**Comment by redouane-dziri** [comment]
COOOOL

**Comment by arnaudstiegler** [comment]
Closing the issue as I tested it on our model, and everything should work now!
