### ISSUE TITLE
Clean up and check everything runs

### ISSUE THREAD

**Issue by redouane-dziri** [redouane-dziri/deep-music-classification#16]
Clean up code where need be and check the notebooks are functional

**Comment by redouane-dziri** [comment]
Cleaned up, corrected and checked all the feature engineering and training. Finishing up the training of the new models and touching up the training notebooks for the last time (will re-run time MFCC overnight for 1,000 epochs).

**Comment by redouane-dziri** [comment]
We will need nice evaluation notebooks from the existing ones + one for the final model, factoring out some function into some kind of utils       ____.py    file, since this will be one of the "entry points" of evaluation of the project

**Comment by arnaudstiegler** [comment]
I've finished the evaluation notebooks. It is not that pretty because there are some annoying processes to get data, and tidying up the result dataframes. But all results are there in dataframes

**Comment by redouane-dziri** [comment]
Will close as soon as discrepancy with stacked models is solved, tackling it now
