### ISSUE TITLE
stacked_final model performance issue

### ISSUE THREAD

**Issue by arnaudstiegler** [redouane-dziri/deep-music-classification#19]
Just noticed that the stacked_final model has 36% accuracy on validation set in my evaluation notebook but the last model trained on the notebook in `improvement/training_stacked.ipynb` is way higher. I think this might be due to having the wrong stacked_final model save, but there could potentially be an issue with it. Won't be able to deal with that until Tuesday

**Comment by redouane-dziri** [comment]
I am re-running training and saving the model :) hopefully you won't have to deal with it

**Comment by redouane-dziri** [comment]
Figured out where the discrepancy comes from! The stacked model requires normalized input, so I just added a normalization operation before feeding the test data to predict on and now the accuracy is pretty much the same as the concatenated model!

**Comment by redouane-dziri** [comment]
You can close this once you've seen my reply if you have no questions :)
