### ISSUE TITLE
Runtime warning in Quantize function

### ISSUE THREAD

**Issue by arnaudstiegler** [redouane-dziri/deep-music-classification#8]
`/Users/arnaud.stiegler/Desktop/deep-music-classification/utils/utils.py:121: RuntimeWarning: divide by zero encountered in log10
  np.log10(a_min), np.log10(a_max), num=n_levels+1
/anaconda3/envs/music_classification/lib/python3.6/site-packages/numpy/core/function_base.py:159: RuntimeWarning: invalid value encountered in multiply
  y *= step
/anaconda3/envs/music_classification/lib/python3.6/site-packages/numpy/core/function_base.py:168: RuntimeWarning: invalid value encountered in add
  y += start`

**Comment by arnaudstiegler** [comment]
It's no big deal but I ran through this issue during preprocessing the dataset (just a warning though so it kept on running).

I think it is just due to having np.log10() which will throw an error when a_min=0. So we could just fix that by adding epsilon to it (although it is not that trivial since the a_min value has some importance for the entire process).

**Comment by redouane-dziri** [comment]
Yes, that is a big deal indeed! So resolving this by:
- computing the bins with a `logspace` between `log10(min+eps)` and `log10(max+eps)` 
- and then changing the first element to `-np.Inf` and the last one to `np.Inf`
That way we don't have to worry about whether the min or max are excluded of the bins, and no more issue of either being zero
